### PR TITLE
Turn dest into a file, because compile-java treats it as such.

### PR DESCRIPTION
**Pull request by pepijndevos**
...

### CODE REVIEW

**Comment by ninjudd** [comment]
This should not be necessary with the latest version of cake in develop. Which version of cake are you using?

**Comment by pepijndevos** [comment]
How do I get that? I tried both brew and gem, which give me 0.6.3 or something. I tried brew with the --HEAD option, which was a disaster. It still gives that error with HEAD, it seems.

**Comment by ninjudd** [comment]
there are instructions on the wiki for installing via git.

**Comment by pepijndevos** [comment]
I had some trouble with the symlink for some reason, but that works now. Now subproject dependencies seem not to work, but that is another issue. Question is, can you assume everyone to have a dev cake, or at least the latest version?

**Comment by ninjudd** [comment]
We are planning to release the next stable version of cake soon. But I do need to add a required version option for plugins.

please file a separate issue for the subprojects bug.

**Comment by ninjudd** [comment]
This should now work with cake stable. Plus, since we are migrating to lein, I'm going to close this.

**Pull request closed without merging**
