### PR TITLE
Lein2 Compatibility

### PR DESCRIPTION
**Pull request by Moocar**
Upgraded to Clojure 1.3.0
Made compatible with Lein2

### CODE REVIEW

**Comment by ninjudd** [comment]
@Raynes, can you take a look at these when you get some time?

**Comment by Raynes** [comment]
@ninjudd I'll test asap, but his lein changes look fine. You'll have to take a look though because he changed some stuff in the protobuf code that I have utterly zero understanding of.

This is excellent though. I can finally move Jiraph to lein 2 when this is merged. @amalloy will be pleased.

**Comment by Moocar** [comment]
Yeah, it appears that in Clojure 1.3, "without" and "assocEx" don't through checked exceptions anymore, so I just replaced it with a RuntimeException. I also have zero understanding of the inner protobuf java code. Gets the "Works on my machine" stamp atleast :)

**Comment by Raynes** [comment]
Merged this in and fixed some issues, etc. Thanks!

**Pull request closed without merging**
